name: Nightly Build

on:
    schedule:
      - cron: '0 0 * * *' # Executes at midnight every day

jobs:
  build:
    runs-on: macos-latest

    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npm run cy:run -- --record --key $CYPRESS_RECORD_KEY

      